# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObejctBasedChangeDetector
                                 A QGIS plugin
 This plugin involves image segmentation to create objects, calculating object features (spectral, texture), and applying classification or comparison methods to determine changes between temporal datasets.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-23
        copyright            : (C) 2026 by Saksham Grover
        email                : groversaksham05@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ObejctBasedChangeDetector class from file ObejctBasedChangeDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ChangeDetector import ObejctBasedChangeDetector
    return ObejctBasedChangeDetector(iface)
