# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObejctBasedChangeDetectorDialog
                                 A QGIS plugin
 This plugin involves image segmentation to create objects, calculating object features (spectral, texture), and applying classification or comparison methods to determine changes between temporal datasets.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Saksham Grover
        email                : groversaksham05@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from skimage.feature import graycomatrix, graycoprops
import os
# pyrefly: ignore [missing-import]
from PyQt5.QtGui import QPixmap,QImage
# pyrefly: ignore [missing-import]
from PyQt5.QtCore import Qt
# pyrefly: ignore [missing-import]
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from osgeo import gdal
from rasterio.transform import Affine
# pyrefly: ignore [missing-import]
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.core import QgsRasterLayer, QgsProject
from qgis.core import QgsVectorLayer
import numpy as np
import rasterio
from skimage.segmentation import slic
from skimage import graph
import geopandas as gpd
# pyrefly: ignore [missing-import]
from rasterio.features import shapes
# pyrefly: ignore [missing-import]
from qgis.core import QgsMessageLog, Qgis
import cv2
from skimage.filters import gabor



# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ChangeDetector_dialog_base.ui'))


class ObejctBasedChangeDetectorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ObejctBasedChangeDetectorDialog, self).__init__(parent)
        self.setupUi(self)
        self.image_data = {}
        self.browseOutputButton.clicked.connect(self.select_output_directory)
        self.comboBox_segmentation.currentTextChanged.connect(self.update_segmentation_parameters)
        self.browseDate1Button.clicked.connect(lambda: self.browse_and_load_image(self.date1LineEdit, self.image_label_1,))
        self.browseDate2Button.clicked.connect(lambda: self.browse_and_load_image(self.date2LineEdit, self.image_label_2,))
        self.comboRedBand.currentIndexChanged.connect(self.update_preview)
        self.comboGreenBand.currentIndexChanged.connect(self.update_preview)
        self.comboBlueBand.currentIndexChanged.connect(self.update_preview)
        self.okButton.clicked.connect(self.run_segmentation)
        self.update_segmentation_parameters()

    def select_output_directory(self):
        folder_path = QFileDialog.getExistingDirectory(
            self,
            "Select Output Directory"
        )

        if folder_path:
            self.outputDirLineEdit.setText(folder_path)
    
    def browse_and_load_image(self, target_lineedit, target_label):

        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Select Raster Image",
            "",
            "Raster Files (*.tif *.tiff *.img *.vrt *.jpg *.png)"
        )

        if not file_path:
            return

        target_lineedit.setText(file_path)

        #  Add FULL raster to QGIS (no RGB override)
        layer_name = os.path.basename(file_path)
        self.add_raster_layer(file_path, layer_name)

        dataset = gdal.Open(file_path)
        if dataset is None:
            return

        band_count = dataset.RasterCount
        key = target_label.objectName()

        cached_bands = []

        #  Read LOW-RES preview ONCE (fast)
        for i in range(1, band_count + 1):
            band = dataset.GetRasterBand(i)

            arr = band.ReadAsArray(
                buf_xsize=600,
                buf_ysize=600
            )

            cached_bands.append(arr)

        # Store in cache
        self.image_data[key] = {
            "bands": cached_bands,
            "label": target_label
        }

        # Populate dropdowns
        self.populate_rgb_band_options(band_count)

        # Initial preview
        self.update_preview()


    # --------------------------------------------------
    # Add FULL raster to QGIS
    # --------------------------------------------------
    def add_raster_layer(self, file_path, layer_name):

        layer = QgsRasterLayer(file_path, layer_name)

        if not layer.isValid():
            return

        #  No renderer → keeps full VRT bands
        QgsProject.instance().addMapLayer(layer)


# --------------------------------------------------
#  Populate RGB dropdowns
# --------------------------------------------------
    def populate_rgb_band_options(self, band_count):
        self.comboRedBand.blockSignals(True)
        self.comboGreenBand.blockSignals(True)
        self.comboBlueBand.blockSignals(True)

        self.comboRedBand.clear()
        self.comboGreenBand.clear()
        self.comboBlueBand.clear()

        for i in range(1, band_count + 1):
            text = f"Band {i}"
            self.comboRedBand.addItem(text)
            self.comboGreenBand.addItem(text)
            self.comboBlueBand.addItem(text)

        # Default selection
        if band_count >= 4:
            self.comboRedBand.setCurrentIndex(3)
            self.comboGreenBand.setCurrentIndex(2)
            self.comboBlueBand.setCurrentIndex(1)
        elif band_count == 3:
            self.comboRedBand.setCurrentIndex(0)
            self.comboGreenBand.setCurrentIndex(1)
            self.comboBlueBand.setCurrentIndex(2)
        elif band_count == 1:
            self.comboRedBand.setCurrentIndex(0)
            self.comboGreenBand.setCurrentIndex(0)
            self.comboBlueBand.setCurrentIndex(0)

        self.comboRedBand.blockSignals(False)
        self.comboGreenBand.blockSignals(False)
        self.comboBlueBand.blockSignals(False)


    # --------------------------------------------------
    # ⚡ FAST Preview (uses cache only)
    # --------------------------------------------------
    def update_preview(self):

        if not self.image_data:
            return

        r = self.comboRedBand.currentIndex()
        g = self.comboGreenBand.currentIndex()
        b = self.comboBlueBand.currentIndex()

        for key in self.image_data:
            data = self.image_data[key]

            bands = data["bands"]
            label = data["label"]

            try:
                r_arr = bands[r]
                g_arr = bands[g]
                b_arr = bands[b]
            except:
                continue

            rgb = np.dstack([
                self.normalize(r_arr),
                self.normalize(g_arr),
                self.normalize(b_arr)
            ])

            rgb = np.ascontiguousarray(rgb)

            h, w, _ = rgb.shape

            qimg = QImage(rgb.data, w, h, 3 * w, QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimg)

            label.setPixmap(pixmap)
            label.setScaledContents(True)
    
    def display_output_preview(self, raster_path):
        dataset = gdal.Open(raster_path)
        if dataset is None:
            return
        bands = []
        band_count = min(3, dataset.RasterCount)
        for i in range(1, band_count + 1):
            band = dataset.GetRasterBand(i)
            arr = band.ReadAsArray(
                buf_xsize=600,
                buf_ysize=600)
            bands.append(arr)
        if band_count == 1:
            arr = self.normalize(bands[0])
            rgb = np.dstack([arr, arr, arr])
        elif band_count == 2:
            # Pad the third channel with zeros
            r_arr = self.normalize(bands[0])
            g_arr = self.normalize(bands[1])
            b_arr = np.zeros_like(r_arr)
            rgb = np.dstack([r_arr, g_arr, b_arr])
        else:
            rgb = np.dstack([
                bands[0],
                bands[1],
                bands[2]])
 

        rgb = np.ascontiguousarray(rgb)
        h, w, _ = rgb.shape
        qimg = QImage(
            rgb.data,
            w,
            h,
            3 * w,
            QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(qimg)

        # REPLACE DATE 2 PREVIEW
        self.image_label_2.setPixmap(pixmap)
        self.image_label_2.setScaledContents(True)

# --------------------------------------------------
# 🎚️ Normalize band values
# --------------------------------------------------
    def normalize(self, arr):

        arr = arr.astype(np.float32)

        min_val = arr.min()
        max_val = arr.max()

        if max_val - min_val == 0:
            return np.zeros_like(arr, dtype=np.uint8)

        return ((arr - min_val) / (max_val - min_val) * 255).astype(np.uint8)

    def update_segmentation_parameters(self):
        selected_algorithm = self.comboBox_segmentation.currentText()

        if selected_algorithm == "SLIC + RAG":
            self.compactnessLabel.show()
            self.compactnessLineEdit.show()

            self.segmentsLabel.show()
            self.segmentsLineEdit.show()

            self.sigmaLabel.show()
            self.sigmaLineEdit.show()

        else:
            self.compactnessLabel.hide()
            self.compactnessLineEdit.hide()

            self.segmentsLabel.hide()
            self.segmentsLineEdit.hide()

            self.sigmaLabel.hide()
            self.sigmaLineEdit.hide()

    def run_segmentation(self):
        algorithm = self.comboBox_segmentation.currentText()

        if "slic" in algorithm.lower():
            self.run_slic_rag_segmentation()

    def run_slic_rag_segmentation(self):
        spectral_selected = self.checkBox_spectral.isChecked()
        glcm_selected = self.radioButton_glcm.isChecked()
        gabor_selected = self.radioButton_gabor.isChecked()
        tamura_selected = self.radioButton_tamura.isChecked()
        image_path = self.date1LineEdit.text()
        output_dir = self.outputDirLineEdit.text()
        n_segments=int(self.segmentsLineEdit.text())
        compactness=int(self.compactnessLineEdit.text())
        sigma = int(self.sigmaLineEdit.text())
        image2_path = self.date2LineEdit.text()
        if not image2_path:
            QMessageBox.warning(self, "Warning", "Please select a Date 2 image.")
            return

        with rasterio.open(image_path) as src:
            image = src.read([1, 2, 3])
            mask = src.dataset_mask()
            original_transform = src.transform
            crs = src.crs
            is_georeferenced = src.crs is not None
        if not is_georeferenced:
            transform = Affine(1.0, 0.0, 0.0, 0.0, -1.0, 0.0)
        else:
            transform = original_transform

        with rasterio.open(image2_path) as src2:
            image2 = src2.read([1, 2, 3])

        if image.shape != image2.shape:
            QMessageBox.critical(self, "Error", "Date 1 and Date 2 images must have the same spatial dimensions.")
            return

        image = np.transpose(image, (1, 2, 0))
        image2 = np.transpose(image2, (1, 2, 0))
        valid_mask = mask > 0

        self.progressBar.setValue(20)

        segments = slic(
            image,
            n_segments=n_segments,
            compactness=compactness,
            sigma=sigma,
            start_label=1,
            mask=valid_mask)

        self.progressBar.setValue(40)

        rag = graph.rag_mean_color(image, segments)
        if 0 in rag:
            rag.remove_node(0)

        features_dict = {}

        for region in np.unique(segments):
            if region == 0:
                continue
            mask = segments == region
            pixels = image[mask]
            mean_color = pixels.mean(axis=0)
            std_texture = pixels.std(axis=0)
            features_dict[region] = np.concatenate([mean_color, std_texture])

        self.progressBar.setValue(60)

        for edge in rag.edges:
            n1, n2 = edge
            diff = np.linalg.norm(features_dict[n1] - features_dict[n2])
            rag[n1][n2]['weight'] = diff

        def weight_mean_color(graph_obj, src, dst, n):
            default = {'weight': 0.0}

            weight_src = graph_obj[src].get(n, default)['weight']
            weight_dst = graph_obj[dst].get(n, default)['weight']

            return {
                'weight': (weight_src + weight_dst) / 2.0
            }

        def merge_boundary(graph_obj, src, dst):
            pass
        
        self.progressBar.setValue(80)
        
        labels2 = graph.merge_hierarchical(
        segments,
        rag,
        thresh=4.205,
        rag_copy=True,
        in_place_merge=False,
        merge_func=merge_boundary,
        weight_func=weight_mean_color)

        mean_raster = np.zeros_like(image, dtype=np.float32)
        unique_segments = np.unique(labels2)

        for seg_id in unique_segments:
            mask = labels2 == seg_id
            pixels = image[mask]
            mean_vals = pixels.mean(axis=0)
            mean_raster[mask] = mean_vals

        mean_raster = mean_raster.astype(np.uint8)
        mean_output_path = os.path.join(output_dir,"object_mean_raster.tif")
        output_path = os.path.join(output_dir, "slic_rag_output.tif")

        with rasterio.open(image_path) as src:
            profile = src.profile.copy()
            labels2[~valid_mask] = 0

            profile.update(
                driver='GTiff',
                height=labels2.shape[0],
                width=labels2.shape[1],
                count=1,
                dtype=rasterio.int32,
                nodata=0,
                transform=transform,
                compress='lzw')
            with rasterio.open(output_path, "w", **profile) as dst:
                dst.write(labels2.astype(rasterio.int32), 1)
        
        with rasterio.open(image_path) as src:
            mean_profile = src.profile.copy()
            mean_profile.update(
                driver='GTiff',
                height=mean_raster.shape[0],
                width=mean_raster.shape[1],
                count=3,
                dtype=rasterio.uint8,
                transform=transform,
                compress='lzw'
            )
            with rasterio.open(mean_output_path,"w",**mean_profile) as dst:
                dst.write(mean_raster[:, :, 0], 1)
                dst.write(mean_raster[:, :, 1], 2)
                dst.write(mean_raster[:, :, 2], 3)

        self.display_output_preview(mean_output_path)
        labels2 = labels2.astype(np.int32)


        # --------------------------------------------------
        # FEATURE EXTRACTION
        # --------------------------------------------------

        def get_glcm_features(region):
            if region.shape[0] < 2 or region.shape[1] < 2:
                return 0, 0, 0, 0
            glcm = graycomatrix(
                region,
                distances=[1],
                angles=[0],
                levels=256,
                symmetric=True,
                normed=True
            )
            contrast = float(graycoprops(glcm, 'contrast')[0, 0])
            homogeneity = float(graycoprops(glcm, 'homogeneity')[0, 0])
            energy = float(graycoprops(glcm, 'energy')[0, 0])
            correlation = float(graycoprops(glcm, 'correlation')[0, 0])

            return contrast, homogeneity, energy, correlation

        results_d1 = []
        results_d2 = []
        feature_dict_d1 = {}
        feature_dict_d2 = {}
        unique_segments = np.unique(labels2)

        for seg_val in unique_segments:
            if seg_val == 0:
                continue
            mask = labels2 == seg_val
            properties_d1 = {
                'label': int(seg_val)
            }
            properties_d2 = {
                'label': int(seg_val)
            }
            # ==================================================
            # SPECTRAL FEATURES
            # ==================================================

            if spectral_selected:
                mean_r1 = float(image[:, :, 0][mask].mean())
                mean_g1 = float(image[:, :, 1][mask].mean())
                mean_b1 = float(image[:, :, 2][mask].mean())

                std_r1 = float(image[:, :, 0][mask].std())
                std_g1 = float(image[:, :, 1][mask].std())
                std_b1 = float(image[:, :, 2][mask].std())

                properties_d1.update({
                    'mean_red': mean_r1,
                    'mean_green': mean_g1,
                    'mean_blue': mean_b1,
                    'std_red': std_r1,
                    'std_green': std_g1,
                    'std_blue': std_b1
                })

                mean_r2 = float(image2[:, :, 0][mask].mean())
                mean_g2 = float(image2[:, :, 1][mask].mean())
                mean_b2 = float(image2[:, :, 2][mask].mean())

                std_r2 = float(image2[:, :, 0][mask].std())
                std_g2 = float(image2[:, :, 1][mask].std())
                std_b2 = float(image2[:, :, 2][mask].std())

                properties_d2.update({
                    'mean_red': mean_r2,
                    'mean_green': mean_g2,
                    'mean_blue': mean_b2,
                    'std_red': std_r2,
                    'std_green': std_g2,
                    'std_blue': std_b2
                })

            # ==================================================
            # BOUNDING BOX
            # ==================================================

            coords = np.where(mask)
            if coords[0].size == 0:
                continue

            minr, maxr = coords[0].min(), coords[0].max()
            minc, maxc = coords[1].min(), coords[1].max()

            local_mask = mask[minr:maxr+1, minc:maxc+1]

            red1 = image[minr:maxr+1, minc:maxc+1, 0].copy()
            green1 = image[minr:maxr+1, minc:maxc+1, 1].copy()
            blue1 = image[minr:maxr+1, minc:maxc+1, 2].copy()

            red1[~local_mask] = 0
            green1[~local_mask] = 0
            blue1[~local_mask] = 0

            red2 = image2[minr:maxr+1, minc:maxc+1, 0].copy()
            green2 = image2[minr:maxr+1, minc:maxc+1, 1].copy()
            blue2 = image2[minr:maxr+1, minc:maxc+1, 2].copy()

            red2[~local_mask] = 0
            green2[~local_mask] = 0
            blue2[~local_mask] = 0

            # ==================================================
            # GLCM FEATURES
            # ==================================================

            if glcm_selected:

                r_feat1 = get_glcm_features(red1.astype(np.uint8))
                g_feat1 = get_glcm_features(green1.astype(np.uint8))
                b_feat1 = get_glcm_features(blue1.astype(np.uint8))

                properties_d1.update({
                    'contrast': float(np.mean([r_feat1[0], g_feat1[0], b_feat1[0]])),
                    'homogeneity': float(np.mean([r_feat1[1], g_feat1[1], b_feat1[1]])),
                    'energy': float(np.mean([r_feat1[2], g_feat1[2], b_feat1[2]])),
                    'correlation': float(np.mean([r_feat1[3], g_feat1[3], b_feat1[3]]))
                })

                r_feat2 = get_glcm_features(red2.astype(np.uint8))
                g_feat2 = get_glcm_features(green2.astype(np.uint8))
                b_feat2 = get_glcm_features(blue2.astype(np.uint8))

                properties_d2.update({
                    'contrast': float(np.mean([r_feat2[0], g_feat2[0], b_feat2[0]])),
                    'homogeneity': float(np.mean([r_feat2[1], g_feat2[1], b_feat2[1]])),
                    'energy': float(np.mean([r_feat2[2], g_feat2[2], b_feat2[2]])),
                    'correlation': float(np.mean([r_feat2[3], g_feat2[3], b_feat2[3]]))
                })

            # ==================================================
            # GABOR FEATURES
            # ==================================================

            elif gabor_selected:

                real_r1, imag_r1 = gabor(red1, frequency=0.2)
                real_g1, imag_g1 = gabor(green1, frequency=0.2)
                real_b1, imag_b1 = gabor(blue1, frequency=0.2)

                mag_r1 = np.sqrt(real_r1**2 + imag_r1**2)
                mag_g1 = np.sqrt(real_g1**2 + imag_g1**2)
                mag_b1 = np.sqrt(real_b1**2 + imag_b1**2)

                phase_r1 = np.arctan2(imag_r1, real_r1)
                phase_g1 = np.arctan2(imag_g1, real_g1)
                phase_b1 = np.arctan2(imag_b1, real_b1)

                properties_d1.update({
                    'gabor_mag_mean': float(np.mean([mag_r1.mean(), mag_g1.mean(), mag_b1.mean()])),
                    'gabor_mag_std': float(np.mean([mag_r1.std(), mag_g1.std(), mag_b1.std()])),
                    'gabor_phase_mean': float(np.mean([phase_r1.mean(), phase_g1.mean(), phase_b1.mean()])),
                    'gabor_phase_std': float(np.mean([phase_r1.std(), phase_g1.std(), phase_b1.std()]))
                })

                real_r2, imag_r2 = gabor(red2, frequency=0.2)
                real_g2, imag_g2 = gabor(green2, frequency=0.2)
                real_b2, imag_b2 = gabor(blue2, frequency=0.2)

                mag_r2 = np.sqrt(real_r2**2 + imag_r2**2)
                mag_g2 = np.sqrt(real_g2**2 + imag_g2**2)
                mag_b2 = np.sqrt(real_b2**2 + imag_b2**2)

                phase_r2 = np.arctan2(imag_r2, real_r2)
                phase_g2 = np.arctan2(imag_g2, real_g2)
                phase_b2 = np.arctan2(imag_b2, real_b2)

                properties_d2.update({
                    'gabor_mag_mean': float(np.mean([mag_r2.mean(), mag_g2.mean(), mag_b2.mean()])),
                    'gabor_mag_std': float(np.mean([mag_r2.std(), mag_g2.std(), mag_b2.std()])),
                    'gabor_phase_mean': float(np.mean([phase_r2.mean(), phase_g2.mean(), phase_b2.mean()])),
                    'gabor_phase_std': float(np.mean([phase_r2.std(), phase_g2.std(), phase_b2.std()]))
                })

            # ==================================================
            # TAMURA FEATURES
            # ==================================================

            elif tamura_selected:

                std1 = np.mean([red1.std(), green1.std(), blue1.std()])
                if std1 == 0:
                    tamura_contrast1 = 0
                else:
                    kurt1 = np.mean((red1 - red1.mean())**4) / (red1.std()**4 + 1e-6)
                    tamura_contrast1 = float(std1 / (kurt1**0.25))

                tamura_coarseness1 = float(np.mean([
                    cv2.Laplacian(red1, cv2.CV_64F).var(),
                    cv2.Laplacian(green1, cv2.CV_64F).var(),
                    cv2.Laplacian(blue1, cv2.CV_64F).var()
                ]))

                properties_d1.update({
                    'tamura_con': tamura_contrast1,
                    'tamura_coarse': tamura_coarseness1
                })

                std2 = np.mean([red2.std(), green2.std(), blue2.std()])
                if std2 == 0:
                    tamura_contrast2 = 0
                else:
                    kurt2 = np.mean((red2 - red2.mean())**4) / (red2.std()**4 + 1e-6)
                    tamura_contrast2 = float(std2 / (kurt2**0.25))

                tamura_coarseness2 = float(np.mean([
                    cv2.Laplacian(red2, cv2.CV_64F).var(),
                    cv2.Laplacian(green2, cv2.CV_64F).var(),
                    cv2.Laplacian(blue2, cv2.CV_64F).var()
                ]))

                properties_d2.update({
                    'tamura_con': tamura_contrast2,
                    'tamura_coarse': tamura_coarseness2
                })
            
            feature_dict_d1[int(seg_val)] = properties_d1
            feature_dict_d2[int(seg_val)] = properties_d2

        for geom, value in shapes(labels2.astype(np.int32),mask=valid_mask,transform=transform):
            if value == 0:
                continue
            properties_d1 = feature_dict_d1.get(int(value), {})
            properties_d2 = feature_dict_d2.get(int(value), {})
            results_d1.append({
                'geometry': geom,
                'properties': properties_d1
            })
            results_d2.append({
                'geometry': geom,
                'properties': properties_d2
            })

        gdf_d1 = gpd.GeoDataFrame.from_features(results_d1)
        gdf_d1.set_crs(crs, inplace=True)

        gdf_d2 = gpd.GeoDataFrame.from_features(results_d2)
        gdf_d2.set_crs(crs, inplace=True)

        vector_output_path_d1 = os.path.join(output_dir, "slic_rag_vector_date1.shp")
        vector_output_path_d2 = os.path.join(output_dir, "slic_rag_vector_date2.shp")

        gdf_d1.to_file(vector_output_path_d1)
        gdf_d2.to_file(vector_output_path_d2)

        layer = QgsRasterLayer(output_path, "SLIC_RAG_Output")

        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        
        mean_layer = QgsRasterLayer(mean_output_path,"Object_Mean_Raster")
        if mean_layer.isValid():
            QgsProject.instance().addMapLayer(mean_layer)

        vector_layer_d1 = QgsVectorLayer(vector_output_path_d1, "SLIC_RAG_Vector_Date1", "ogr")

        if vector_layer_d1.isValid():
            QgsProject.instance().addMapLayer(vector_layer_d1)

        vector_layer_d2 = QgsVectorLayer(vector_output_path_d2, "SLIC_RAG_Vector_Date2", "ogr")

        if vector_layer_d2.isValid():
            QgsProject.instance().addMapLayer(vector_layer_d2)

        self.progressBar.setValue(100)